'''
Base de treinamento inicial.
Para utilizar deve ser adicionada ao banco de dados 
ou descomentar a partir da linha 101 até a 110 do arquivo training_analysis.py
Também deve ser comentado as linha 91 até 99 do mesmo arquivo
Também descomentar a linha 7 do mesmo arquivo que as bases são importadas
'''
training_base_simple = [
    
    # POSITIVO
    ('este trabalho e agradável','positivo'),
    ('gosto de ficar no seu aconchego','positivo'),
    ('fiz a adesão ao curso hoje porque eu gostei','positivo'),
    ('eu sou admirada por muitos','positivo'),
    ('adoro como você e','positivo'),
    ('adoro seu cabelo macio','positivo'),
    ('adoro a cor dos seus olhos','positivo'),
    ('somos tão amáveis um com o outro','positivo'),
    ('sinto uma grande afeição por ele','positivo'),
    ('quero agradar meus filhos','positivo'),
    ('me sinto completamente amado','positivo'),
    ('eu amo você','positivo'),
    ('que grande alivio','positivo'),
    ('feliz ano novo', 'positivo'),
    ('a dor esta amenizando finalmente','positivo'),
    ('acho que me apaixonei','positivo'),
    ('amar e maravilhoso','positivo'),
    ('estou me sentindo muito animada','positivo'),
    ('me sinto muito bem hoje','positivo'),
    ('como o luar e belo','positivo'),
    ('o dia esta muito bonito','positivo'),
    ('nossa como sou afortunado','positivo'),
    ('as maravilhas do mundo','positivo'),
    ('recebi muito carinho hoje do meus colegas','positivo'),
    ('estou me sentindo reconfortada hoje','positivo'),
    ('e muito bom estar com os amigos','positivo'),
    ('estou muito contente com o resultado dos testes','positivo'),
    ('essa pintura esta bem brilhante otimo trabalho','positivo'),
    ('temos água em abundancia','positivo'),
    ('que roupa delicada','positivo'),
    ('você e um grande comediante','positivo'),
    ('que bondade a sua em vir aqui','positivo'),
    ('o amor e lindo','positivo'),
    ('nossa amizade vai durar para sempre','positivo'),
    ('estou eufórica com a noticia','positivo'),
    ('ele e realmente fiel a mim','positivo'),
    ('vou dar uma grande festa para comemorar meu aniversário','positivo'),
    ('graças a deus que eu enxerguei o certo','positivo'),
    ('essa e a melhor escolhas de todas','positivo'),
    ('o mais incrível e você minha bela','positivo'),
    ('e tão engraçado tentar explicar','positivo'),
    ('e emocionante estar neste lugar','positivo'),
    ('estou cativada pelo seu olhar','positivo'),
    ('estou loucamente apaixonada','positivo'),
    ('eu nunca tive duvidas','positivo'),
    ('estou rodeada pelo seu abraço','positivo'),
    ('eu vejo estrelas pelo caminho','positivo'),
    ('eu sinto o sol sempre que você esta por perto','positivo'),
    ('eu estou sorrindo de orelha a orelha','positivo'),
    ('isso vale a pena','positivo'),
    ('finalmente você colocou meu amor em primeiro lugar','positivo'),
    ('nós dançamos noite adentro','positivo'),
    ('seu amor e brilhante','positivo'),
    ('toquei muitos corações durante o meu caminho','positivo'),
    ('eu serei sua amiga e companheira','positivo'),
    ('você me traz de volta a vida','positivo'),
    ('você e como um sonho doce','positivo'),
    ('adoro este doce de frutas','positivo'),
    ('meu suco favorito','positivo'),
    ('estou agradecida pela ajuda','positivo'),
    ('e um enorme prazer ter você em nossa equipe','positivo'),
    ('trabalhar em equipe e o melhor','positivo'),
    ('me sinto flutuando no ar','positivo'),
    ('a brisa esta agradável hoje','positivo'),
    ('ótimo e compatível','positivo'),
    ('somos compatíveis um com o outro','positivo'),
    ('o órgão e compatível com o paciente','positivo'),
    ('estou contente fui aceita na faculdade','positivo'),
    ('fui aprovada no meu exame','positivo'),
    ('fui beneficiada pela minha empresa','positivo'),
    ('eu sou muito cativante','positivo'),
    ('estou contente com o apoio','positivo'),
    ('como este lugar e confortável','positivo'),
    ('e bom estar quente neste frio','positivo'),
    ('um elogio nunca e demais','positivo'),
    ('vou te chamar para comemorar','positivo'),
    ('e desejável a sua presença em nossa apresentação','positivo'),
    ('sou muito grata a você','positivo'),
    ('me dedico muito naquilo que faço','positivo'),
    ('estou completamente apaixonada ','positivo'),
    ('vamos agitar essa noite ','positivo'),
    ('você significa muito para mim','positivo'),
    ('vamos agir sem preconceitos e julgamentos','positivo'),
    ('finalmente completei a minha coleção, maravilhoso','positivo'),
    ('eu sou sua rainha ','positivo'),
    ('satisfatoriamente eu anuncio o vencedor dos jogos','positivo'),
    ('você me atrai facilmente ','positivo'),
    ('aquele rapaz e extremamente atraente','positivo'),
    ('sinto-me viva ','positivo'),
    ('sinto-me em paz ','positivo'),
    ('estamos tendo muito lucro','positivo'),
    ('muito bem esta tudo em ordem agora ','positivo'),
    ('podemos arrumar um emprego juntos ','positivo'),
    ('a arrumação esta terminada, que alívio','positivo'),
    ('o câncer e benigno ','positivo'),
    ('o amor e abundante','positivo'),
    ('vamos ser caridosos este natal','positivo'),
    ('com todo esse charme você irá atrair a todos','positivo'),
    ('nossa como você e charmoso querido ','positivo'),
    ('sou querida pelos meu amigos','positivo'),
    ('seja cuidadoso com os meus sentimentos','positivo'),
    ('estou comovido com tamanha caridade','positivo'),
    ('um chá quente e reconfortante','positivo'),
    ('que alegria ter vocês aqui ','positivo'),
    ('vamos aplaudir o vencedor ','positivo'),
    ('palmas para a aniversariante','positivo'),
    ('desejo a você tudo de bom','positivo'),
    ('hora de apreciar um bom vinho','positivo'),
    ('aprecio sua presença em minha escola','positivo'),
    ('anseio por seus próximos trabalhos','positivo'),
    ('maravilhoso jogo amistoso','positivo'),
    ('e ótimo que os ânimos tenham se apaziguado','positivo'),
    ('concretizei finalmente meu sonho','positivo'),
    
        # NEUTRO
    ('magicamente você me surpreendeu','neutro'),
    ('e imenso esse globo','neutro'),
    ('uau que noticia bacana', 'neutro'),
    ('uau, eu tambem quero um carro desse para mim', 'neutro'),
    ('eu nao esperava ele me pedir em casamento, que noticia surpreendente', 'neutro'),
    ('sera que iremos conseguir fugir?', 'neutro'),
    ('descobri que estou gravida', 'neutro'),
    ('qual o resultado do teste?', 'neutro'),
    ('fascinante esse filme, eu adorei', 'neutro'),
    ('que susto, eu nao esperava', 'neutro'),
    ('ue, eu achei que iria chover hoje', 'neutro'),
    ('nunca se sabe', 'neutro'),
    ('quem sera o assassino', 'neutro'),
    ('voce nunca sabera se e homem ou mulher', 'neutro'),
    ('isso e tremendamente interessante','neutro'),
    ('meu bilhete for sorteado, inacreditável!','neutro'),
    ('um assalto a mão armada!','neutro'),
    ('incrível, cabe em qualquer lugar!','neutro'),
    ('você por aqui?','neutro'),
    ('não dá pra acreditar no que ela me contou','neutro'),
    ('os convidados já estão chegando!','neutro'),
    ('puxa vida! nunca nos livramos de alguem tão depressa','neutro'),
    ('micha carteira sumiu, eu estava com ela na mão','neutro'),
    ('oh! um disco voador','neutro'),
    ('amigos, que bela neutro!','neutro'),
    ('nunca pensei que veria isso e perto','neutro'),
    ('nem acredito que comi tanto','neutro'),
    ('não acredito que veio me ver','neutro'),
    ('não acredito que e  tão descarado','neutro'),
    ('me surpreende sua falta de tato','neutro'),
    ('o predio onde eles moravam desabou!','neutro'),
    ('inacreditável um bolo tão grande','neutro'),
    ('e serio mesmo? não dá pra acreditar','neutro'),
    ('como assim não vai ao nosso encontro?','neutro'),
    ('como assim não tem ninguem em casa?','neutro'),
    ('ue, mas para onde ele foi?!','neutro'),
    ('por essa eu não esperava','neutro'),
    ('nossa, olha só que mergulho','neutro'),
    ('minha esposa está grávida!','neutro'),
    ('meu dinheiro sumiu!','neutro'),
    ('e verdade que os dois terminaram?!?','neutro'),
    ('caramba, nem vi você chegar','neutro'),
    ('nossa, como pode alguem cozinhar tão mal?','neutro'),
    ('nossa que incrível','neutro'),
    ('a fórmula sumiu!','neutro'),
    ('eu nem acredito que já estou terminando o curso','neutro'),
    ('não acredito que esta aqui comigo novamente','neutro'),
    ('está escondendo algo de nós!','neutro'),
    ('como assim, ainda não terminou a tarefa','neutro'),
    ('pensei que já estivesse pronta!','neutro'),
    ('opa! quem apagou a luz?','neutro'),
    ('caramba! aonde vai tão rápido?','neutro'),
    ('estamos seguindo o caminho errado!','neutro'),
    ('quatro reais o litro da gasolina!','neutro'),
    ('me assustei ao vê-lo desse jeito!','neutro'),
    ('minha mãe está grávida, acredita nisso?','neutro'),
    ('parece mentira você ter crescido tanto','neutro'),
    ('me surpreende sua imaginação','neutro'),
    ('suas roupas são realmente lindas','neutro'),
    ('com consegue ser tão bela?','neutro'),
    ('essa e realmente uma casa deslumbrante','neutro'),
    ('superou minhas expectativas','neutro'),
    ('e admirável a maneira como se comporta','neutro'),
    ('isso e realmente chocante','neutro'),
    ('algumas noticias me surpreenderam no noticiário','neutro'),
    ('surpreendente sua festa','neutro'),
    ('nossa, que top esse filme!, eu nao esperava', 'neutro'),
    ('cheguei atrasado e me assim consegui entregar o resultado, ufa!', 'neutro'),
    ('ufa, essa foi por pouco, quase caimos fora', 'neutro'),
    ('quem sabe na proxima vida', 'neutro'),
    ('estou tremendo de alegria','neutro'),
    ('chocou grande parte do mundo','neutro'),
    ('eu ficaria muito espantado com a sua vinda','neutro'),
    ('ele e admirável','neutro'),
    ('sua beleza me surpreendeu','neutro'),
    ('seus olhos são surpreendentemente verdes','neutro'),
    ('os políticos se surpreendem quando alguem acredita neles','neutro'),
    ('estou perplexa com essas denuncias','neutro'),
    ('fiquei perplexo com suas palavras','neutro'),
    ('estou abismado com sua prosa','neutro'),
    ('eu ficaria realmente abismado se me dissessem isso','neutro'),
    ('o grupo foi surpreendido enquanto lavava o carro','neutro'),
    ('estou boquiaberto com as imagens','neutro'),
    ('estou boquiaberto com essas suas palavras','neutro'),
    ('esse quadro e maravilhoso','neutro'),
    ('este carro me deixou maravilhado','neutro'),
    ('estou maravilhada','neutro'),
    ('pqp, voce e gay?', 'neutro'),
    ('qual sera o meu salario ano que vem?', 'neutro'),
    ('essa expectativa esta me matando','neutro'),
    ('vou caminhar sempre na expectativa de encontrá-lo','neutro'),
    ('você emudece minhas palavras','neutro'),
    ('minhas palavras vão emudecer se não parar de me surpreender','neutro'),
    ('a mulher e um efeito deslumbrante da natureza','neutro'),
    ('estou deslumbrada com essas jóias','neutro'),
    ('isso e romântico e deslumbrante','neutro'),
    ('isso pode ser surpreendentemente deslumbrante','neutro'),
    ('trabalho deslumbrante','neutro'),
    ('essas pessoas são esplêndida','neutro'),
    ('e esplendido como o ceu se encontra no momento','neutro'),
    ('e um carro fantástico','neutro'),
    ('um edifício realmente fantástico','neutro'),
    
        # NEGATIVO
    ('pqp que encheção de saco','negativo'),
    ('quero meu dinheiro de volta','negativo'),
    ('ta pra nascer algo q me de mais dor de cabeça', 'negativo'),
    ('ele a feriu profundamente','negativo'),
    ('eu vou matar ele', 'negativo'),
    ('que droga, eu nao passei de ano na escola, pqp', 'negativo'),
    ('pqp, tomei dez multas de transito', 'negativo'),
    ('que droga, perdi tudo no cassino', 'negativo'),
    ('me roubaram na rua', 'negativo'),
    ('esse trouxa me deixou esperando', 'negativo'),
    ('vou despejar minha cólera em você','negativo'),
    ('me sinto atormentado','negativo'),
    ('não me contrarie','negativo'),
    ('meu time perdeu ontem', 'negativo'),
    ('so chove nesse lugar, que merda', 'negativo'),
    ('tirei ferias e fui despedido', 'negativo'),
    ('fui despedido por justa causa', 'negativo'),
    ('vou despedir aquele imcompetente', 'negativo'),
    ('bando de filho da puta, que negativo disso tudo', 'negativo'),
    ('nada mais faz sentido, que droga', 'negativo'),
    ('que lerdeza isso', 'negativo'),
    ('demora demais a fila', 'negativo'),
    ('nunca vai rapido a fila, sempre demora', 'negativo'),
    ('perdi todo meu dinheiro', 'negativo'),
    ('so tem gente feia nessa festa, vamos embora', 'negativo'),
    ('vou destruir tudo  que foi construído','negativo'),
    ('não consigo terminar este trabalho, e muito frustrante','negativo'),
    ('me frustra a sua presença aqui','negativo'),
    ('esta comida me parece muito ruim','negativo'),
    ('você me destrói','negativo'),
    ('estamos separados','negativo'),
    ('estou odiando este vestido','negativo'),
    ('não pude comprar meu celular hoje','negativo'),
    ('ela e uma garota ruim','negativo'),
    ('estivemos em um show horroroso','negativo'),
    ('o ingresso estava muito caro','negativo'),
    ('se eu estragar tudo vai por água a baixo','negativo'),
    ('não possuo dinheiro algum','negativo'),
    ('sou muito pobre','negativo'),
    ('vai prejudicar a todos esta nova medida','negativo'),
    ('ficou ridículo','negativo'),
    ('este sapato esta muito apertado','negativo'),
    ('a musica e uma ofensa aos meus ouvidos','negativo'),
    ('não consigo terminar uma tarefa muito difícil','negativo'),
    ('reprovei em minha graduação','negativo'),
    ('estou muito chateado com tudo','negativo'),
    ('eu odeio em você','negativo'),
    ('e um desprazer conhecê-lo','negativo'),
    ('estou desperdiçando minhas ferias','negativo'),
    ('e muito ruim este jogo','negativo'),
    ('vamos ter muito rancor pela frente','negativo'),
    ('não achei que seria tão terrível','negativo'),
    ('vou vetar o orçamento ao cliente','negativo'),
    ('meus pais não consentiram nosso casamento','negativo'),
    ('eu odiei este perfume','negativo'),
    ('seu descaso e frustrante','negativo'),
    ('me sinto completamente amarga','negativo'),
    ('desprezo muito o seu trabalho','negativo'),
    ('estamos descontentes por nossa família','negativo'),
    ('vou infernizar a sua empresa','negativo'),
    ('estou furioso com estes valores','negativo'),
    ('obrigaram o rapaz a sair','negativo'),
    ('como ele pode deixar de lado?','negativo'),
    ('são apenas injurias sobre mim','negativo'),
    ('estou enfurecido com a situação dessa empresa','negativo'),
    ('estou com o diabo no corpo','negativo'),
    ('isso foi diabólico','negativo'),
    ('tenho aversão à gente chata','negativo'),
    ('não vou perdoar sua traição','negativo'),
    ('esse dinheiro sujo e corrupto','negativo'),
    ('eles me crucificam o tempo todo','negativo'),
    ('eu vou enlouquecer com todo este barulho','negativo'),
    ('não agüento todo esse assedio','negativo'),
    ('cólera do dragão','negativo'),
    ('isso e ridículo!','negativo'),
    ('da próxima vez, vou inventar tudo sozinho','negativo'),
    ('seus tolos! deixaram ele escapar!','negativo'),
    ('jamais te perdoarei','negativo'),
    ('o que e isso? outra multa','negativo'),
    ('você passou dos limites!','negativo'),
    ('sente-se e cale a boca','negativo'),
    ('ingratosvermesvocês me pagam!','negativo'),
    ('saiam da dai, se não arranco vocês dai!','negativo'),
    ('você já me causou problemas suficientes','negativo'),
    ('que transito maldito, perdi muito tempo parado aqui nessa porra', 'negativo'),
    ('porra, eu nao quero esperar nada, sai da minha frente', 'negativo'),
    ('a bebida esquentou demais, estou muito puto com essa porra', 'negativo'),
    ('ele me traiu com aquela vadia, filho da puta', 'negativo'),
    ('uma palavra a mais e eu ja mandaria calar a boca', 'negativo'),
    ('eu nao tenho paciencia com gente lerda e burra', 'negativo'),
    ('preconceito me da muita raiva, que povo mais escroto', 'negativo'),
    ('estou nervoso com esta situacao, eu nao mereco passar esta barra sozinho, estou para matar alguem', 'negativo'),
    ('eu estou bastante  e mesma assim nao passei no tweet, que merda', 'negativo'),
    ('eu faco dieta e constinuo engordando', 'negativo'),
    ('isso foi a gota d’agua','negativo'),
    ('o que você tem com isso?','negativo'),
    ('não vejo a hora de me livrar de você','negativo'),
    ('já entendi a jogada seus safados!','negativo'),
    ('você não merece piedade','negativo'),
    ('saia de perto de mim','negativo'),
    ('suma daqui, ou arranco seu couro!','negativo'),
    ('estou revoltado com essa situação','negativo'),
    ('seu idiota!','negativo'),
    ('não, eu não vou te emprestar dinheiro!','negativo'),
    ('você não passa de um cafajeste! vai embora','negativo'),
    ('pare de frescura e vá trabalhar','negativo'),
    ('eles merecem uma lição','negativo'),
    ('ainda estou muito bravo com você','negativo'),
    ('eu preciso surrar aquela chantagista','negativo'),
    ('olha o que você fez! derramou!','negativo'),
    ('você está pedindo pra apanhar!','negativo'),
    ('me deixa em paz!','negativo'),
    ('morra maldito, morra!','negativo'),
    ('você e mais irritante de perto','negativo'),
    ('e bom fechar o bico','negativo'),
    ('Meu deus essa faculdade é uma merda','negativo'),
    ('VSF cara você não faz nada direito', 'negativo'),
    ('VSF seu imprestável', 'negativo'),
    ('VSF mano! sai daqui', 'negativo'),
]

training_base_advanced = [
    
    # ALEGRIA
('este trabalho e agradável','alegria'),
('gosto de ficar no seu aconchego','alegria'),
('fiz a adesão ao curso hoje porque eu gostei','alegria'),
('eu sou admirada por muitos','alegria'),
('adoro como você e','alegria'),
('adoro seu cabelo macio','alegria'),
('adoro a cor dos seus olhos','alegria'),
('somos tão amáveis um com o outro','alegria'),
('sinto uma grande afeição por ele','alegria'),
('quero agradar meus filhos','alegria'),
('me sinto completamente amado','alegria'),
('eu amo você','alegria'),
('que grande alivio','alegria'),
('feliz ano novo', 'alegria'),
('a dor esta amenizando finalmente','alegria'),
('acho que me apaixonei','alegria'),
('amar e maravilhoso','alegria'),
('estou me sentindo muito animada','alegria'),
('me sinto muito bem hoje','alegria'),
('como o luar e belo','alegria'),
('o dia esta muito bonito','alegria'),
('nossa como sou afortunado','alegria'),
('as maravilhas do mundo','alegria'),
('recebi muito carinho hoje do meus colegas','alegria'),
('estou me sentindo reconfortada hoje','alegria'),
('e muito bom estar com os amigos','alegria'),
('estou muito contente com o resultado dos testes','alegria'),
('essa pintura esta bem brilhante otimo trabalho','alegria'),
('temos água em abundancia','alegria'),
('que roupa delicada','alegria'),
('você e um grande comediante','alegria'),
('que bondade a sua em vir aqui','alegria'),
('o amor e lindo','alegria'),
('nossa amizade vai durar para sempre','alegria'),
('estou eufórica com a noticia','alegria'),
('ele e realmente fiel a mim','alegria'),
('vou dar uma grande festa para comemorar meu aniversário','alegria'),
('graças a deus que eu enxerguei o certo','alegria'),
('essa e a melhor escolhas de todas','alegria'),
('o mais incrível e você minha bela','alegria'),
('e tão engraçado tentar explicar','alegria'),
('e emocionante estar neste lugar','alegria'),
('estou cativada pelo seu olhar','alegria'),
('estou loucamente apaixonada','alegria'),
('eu nunca tive duvidas','alegria'),
('estou rodeada pelo seu abraço','alegria'),
('eu vejo estrelas pelo caminho','alegria'),
('eu sinto o sol sempre que você esta por perto','alegria'),
('eu estou sorrindo de orelha a orelha','alegria'),
('isso vale a pena','alegria'),
('finalmente você colocou meu amor em primeiro lugar','alegria'),
('nós dançamos noite adentro','alegria'),
('seu amor e brilhante','alegria'),
('toquei muitos corações durante o meu caminho','alegria'),
('eu serei sua amiga e companheira','alegria'),
('você me traz de volta a vida','alegria'),
('você e como um sonho doce','alegria'),
('adoro este doce de frutas','alegria'),
('meu suco favorito','alegria'),
('estou agradecida pela ajuda','alegria'),
('e um enorme prazer ter você em nossa equipe','alegria'),
('trabalhar em equipe e o melhor','alegria'),
('me sinto flutuando no ar','alegria'),
('a brisa esta agradável hoje','alegria'),
('ótimo e compatível','alegria'),
('somos compatíveis um com o outro','alegria'),
('o órgão e compatível com o paciente','alegria'),
('estou contente fui aceita na faculdade','alegria'),
('fui aprovada no meu exame','alegria'),
('fui beneficiada pela minha empresa','alegria'),
('eu sou muito cativante','alegria'),
('estou contente com o apoio','alegria'),
('como este lugar e confortável','alegria'),
('e bom estar quente neste frio','alegria'),
('um elogio nunca e demais','alegria'),
('vou te chamar para comemorar','alegria'),
('e desejável a sua presença em nossa apresentação','alegria'),
('sou muito grata a você','alegria'),
('me dedico muito naquilo que faço','alegria'),
('estou completamente apaixonada ','alegria'),
('vamos agitar essa noite ','alegria'),
('você significa muito para mim','alegria'),
('vamos agir sem preconceitos e julgamentos','alegria'),
('finalmente completei a minha coleção, maravilhoso','alegria'),
('eu sou sua rainha ','alegria'),
('satisfatoriamente eu anuncio o vencedor dos jogos','alegria'),
('você me atrai facilmente ','alegria'),
('aquele rapaz e extremamente atraente','alegria'),
('sinto-me viva ','alegria'),
('sinto-me em paz ','alegria'),
('estamos tendo muito lucro','alegria'),
('muito bem esta tudo em ordem agora ','alegria'),
('podemos arrumar um emprego juntos ','alegria'),
('a arrumação esta terminada, que alívio','alegria'),
('o câncer e benigno ','alegria'),
('o amor e abundante','alegria'),
('vamos ser caridosos este natal','alegria'),
('com todo esse charme você irá atrair a todos','alegria'),
('nossa como você e charmoso querido ','alegria'),
('sou querida pelos meu amigos','alegria'),
('seja cuidadoso com os meus sentimentos','alegria'),
('estou comovido com tamanha caridade','alegria'),
('um chá quente e reconfortante','alegria'),
('que alegria ter vocês aqui ','alegria'),
('vamos aplaudir o vencedor ','alegria'),
('palmas para a aniversariante','alegria'),
('desejo a você tudo de bom','alegria'),
('hora de apreciar um bom vinho','alegria'),
('aprecio sua presença em minha escola','alegria'),
('anseio por seus próximos trabalhos','alegria'),
('maravilhoso jogo amistoso','alegria'),
('e ótimo que os ânimos tenham se apaziguado','alegria'),
('concretizei finalmente meu sonho','alegria'),


    #NOJO
('você e abominável','nojo'),
('nossa, que vontade de vomitar', 'nojo'),
('que banheiro porco', 'nojo'),
('eu caguei nas calcas', 'nojo'),
('bebi demais e preciso vomitar', 'nojo'),
('esta saindo pus do ferimento', 'nojo'),
('ele tem frieria e micose no pe', 'nojo'),
('o povo da praia ao lado joga tudo no chao, bando de porco', 'nojo'),
('abomino a maneira como você age','nojo'),
('estou adoentado','nojo'),
('meu pai esta adoentado','nojo'),
('estamos todos doentes','nojo'),
('essa situação e muito amarga','nojo'),
('disse adeus amargamente','nojo'),
('tenho antipatia por aquela pessoa','nojo'),
('como pode ser tão antipática!','nojo'),
('que horrível seu asqueroso','nojo'),
('tenho aversão agente como você','nojo'),
('isso tudo e só chateação','nojo'),
('estou muito chateada com suas mentiras','nojo'),
('tão desagradável','nojo'),
('isso me desagrada completamente','nojo'),
('te desagrada isso','nojo'),
('estou com enjôos terríveis','nojo'),
('todos estão enfermos','nojo'),
('foi uma enfermidade terrível','nojo'),
('isso e muito grave','nojo'),
('não seja tão grosseiro','nojo'),
('você fez uma manobra ilegal','nojo'),
('sua indecente, não tem vergonha?','nojo'),
('você e malvado com as crianças','nojo'),
('que comentário maldoso','nojo'),
('sem escrúpulos você manipula a tudo','nojo'),
('sinto repulsa por você','nojo'),
('e repulsivo a maneira como olha para as pessoas','nojo'),
('estou indisposta','nojo'),
('a indisposição me atacou hoje','nojo'),
('acho que vou vomitar','nojo'),
('tem muito vomito lá','nojo'),
('que incomodo essa dor','nojo'),
('não me incomode nunca mais','nojo'),
('suas bobagens estão nos incomodando','nojo'),
('que nojo olha toda essa sujeira','nojo'),
('como isso está sujo','nojo'),
('tenho náuseas só de lembrar','nojo'),
('me sinto nauseada com o cheiro desta comida','nojo'),
('você esta obstruindo a passagem de ar','nojo'),
('você esta terrivelmente doente','nojo'),
('olhe que feia esta roupa','nojo'),
('que atitude deplorável','nojo'),
('nossa como você e feio','nojo'),
('muito mau tudo isso','nojo'),
('estou nojoso com você','nojo'),
('você cortou o meu assunto','nojo'),
('para que tanta chateação?','nojo'),
('esse perfume e enjoativo','nojo'),
('ser perigoso não nada bom','nojo'),
('você e perigoso demais para minha filhas','nojo'),
('que fetido este esgoto','nojo'),
('que fedido você esta','nojo'),
('que cachorro malcheiroso','nojo'),
('hora que ultraje','nojo'),
('e ultrajante da sua parte','nojo'),
('situação desagradável essa','nojo'),
('você só me da nojo','nojo'),
('tenho aversão a pessoas assim','nojo'),
('antipatia e um mal da sociedade','nojo'),
('que criatura abominável','nojo'),
('e depressiva a maneira como você vê o mundo','nojo'),
('me desagrada sua presença na festa','nojo'),
('sinto asco dessa coisa','nojo'),
('que hediondo!','nojo'),
('vou golfar o cafe fora','nojo'),
('hora que garota detestável!','nojo'),
('estou nauseada','nojo'),
('isso que você disse foi muito grave','nojo'),
('não seja obsceno na frente das crianças','nojo'),
('não seja rude com as visitas','nojo'),
('esse assunto me da repulsa','nojo'),
('que criança terrivelmente travessa','nojo'),
('que criança mal educada','nojo'),
('estou indisposta te dar o divorcio','nojo'),
('tão patetico, não tem nada mais rude para dizer?','nojo'),
('por motivo torpe, com emprego de meio cruel e com impossibilidade de defesa para a vítima','nojo'),
('a inveja e tão vil e vergonhosa que ninguem se atreve a confessá-la','nojo'),
('o miserável receio de ser sentimental e o mais vil de todos os receios modernos','nojo'),
('travesso gato quando fica com saudades do dono mija no sapato','nojo'),
('isso e um ato detestável e covarde','nojo'),
('revelam apenas o que e destrutivo e detestável para o povo','nojo'),
('não sei como e a vida de um patife, mais a de um homem honesto e abominável','nojo'),
('há coisas que temos que suportar para não acharmos a vida insuportável','nojo'),
('as injurias do tempo e as injustiças do homem','nojo'),
('odioso e desumano','nojo'),
('você não publicará conteúdo odiento, pornográfico ou ameaçador','nojo'),
('rancoroso e reprimido','nojo'),
('não há animal mais degradante, estúpido, covarde, lamentável, egoísta, rancoroso e invejoso do que o homem','nojo'),
('o virulento debate ente políticos','nojo'),


    # MEDO
('eu imploro, não me matem!','medo'),
('tem certeza que não e perigoso?','medo'),
('ele apontou uma arma para minha cabeca', 'medo'),
('nao quero perder meu emprego, irei ficar pobre', 'medo'),
('engordei dez quilos, nao quero ser gordo', 'medo'),
('sera que aqui tem fantasma?', 'medo'),
('eu nao entro no cemiterio nem morto', 'medo'),
('encosto e esperito exitem', 'medo'),
('fantasma e do mau', 'medo'),
('o guima e cagao', 'medo'),
('fantasma me da medo', 'medo'),
('ferrou, o aviao esta caindo e vamos morrer', 'medo'),
('eu me cago de medo de entrar na favela sozinho', 'medo'),
('tenho pavor de parque de diversoes, os brinquedos sao muito altos', 'medo'),
('socorro, tem ladroes entrando em casa', 'medo'),
('uma facada deve doer mais que um tiro', 'medo'),
('tenho medo de ficar pobre e nao ter seguranca para minha familia', 'medo'),
('qual a necessidade dessa violencia, alguem pode se machucar fortemente', 'medo'),
('estranho alguem ter medo de chachorro, eles nao sao bravos', 'medo'),
('eu nao pulo de para-quedas nem morto, morro de medo', 'medo'),
('os presos la no pais Afeganistao sao torturados e sao quase mortos', 'medo'),
('os bandidos estao morando aqui no bairro, proximo a favela', 'medo'),
('eu nao posso perder ela, eu amo demais para ficar longe', 'medo'),
('socorro, eu vi um fantasma', 'medo'),
('eu tenho pavor de mar,morro de medo de me afogar', 'medo'),
('beira de abismo e loucura', 'medo'),
('acabou a luz e fiquei com medo', 'medo'),
('existe muitas pessoas ruins no mundo', 'medo'),
('no mato ao lado de casa tem cobra e aranha, e perigoso', 'medo'),
('eu nao saio sozinha de noite, so tem louco na rua', 'medo'),
('arma de fogo e faca sao perigosos', 'medo'),
('não tenho certeza se e seguro','medo'),
('tenho que correr pra não me pegarem','medo'),
('socorro! ele queria roubar os meus doces!','medo'),
('esse cara está me perseguindo','medo'),
('não entro lá, e um lugar muito perigoso','medo'),
('este lugar continua assustador','medo'),
('na selva tem muitos animais perigosos','medo'),
('avancem com cautela','medo'),
('este lugar está silencioso de mais, cuidado!','medo'),
('por favor, deixe-me viver!','medo'),
('vou ficar sem mesada se tirar nota baixa','medo'),
('parece que tem olhos nos vigiando','medo'),
('eu temo que a sentença do juiz possa ser negativa','medo'),
('mas essa missão e arriscada','medo'),
('salvem-se quem puder!','medo'),
('meu plano pode ser descoberto','medo'),
('não tive culpa, juro não fui eu','medo'),
('tenho que tomar cuidado com o lobisomem','medo'),
('se eu não achar, ele vai descobrir a verdade','medo'),
('meu deus, ele desapareceu!','medo'),
('tomara que eles não me vejam daqui!','medo'),
('mantenha isso em segredo, se descobrirem estaremos ferrados','medo'),
('por favor, me soltem, eu sou inocente','medo'),
('estou ouvindo passos atrás de mim','medo'),
('eu vou pedir socorro!','medo'),
('cuidado com as curvas na estrada','medo'),
('não sei não, parece perigoso','medo'),
('estou tremendo de medo!','medo'),
('socorro, eu vou cair!','medo'),
('eu não vou ate a floresta negra, e muito perigoso','medo'),
('ouço passos na minha direção','medo'),
('acho que está arriscado de mais','medo'),
('vamos voltar, e muito perigoso','medo'),
('fuja, se não acabaremos mortos','medo'),
('receio por não me livrar desta situação','medo'),
('socorro! ele está armado!','medo'),
('ei cuidado, você vai bater no poste!','medo'),
('socorro, nós estamos afundando','medo'),
('e serio, cuidado com essa arma!','medo'),
('os tubarões estão atacando!','medo'),
('sinto arrepios quando fico sozinho no escuro','medo'),
('calma, eu não estou com o dinheiro','medo'),
('eu acho que estou sendo enganado','medo'),
('ligeiro, temos que fugir depressa','medo'),
('tem um crocodilo selvagem vindo para cá','medo'),
('se ficarmos quietos eles não vão nos achar','medo'),
('fuja! o tigre parece faminto','medo'),
('estou sem saída, preciso de um milagre','medo'),
('tire isso de mim! socorro!','medo'),
('não sei nadar, vou me afogar!','medo'),
('não tenho certeza se e seguro','medo'),
('vou apanhar se meus pais verem meu boletim','medo'),
('não consigo sair daqui!','medo'),
('se sair tão tarde, poderei ser assaltada','medo'),
('não me deixe por favor!','medo'),
('espere, não pode me largar aqui sozinho','medo'),
('temo pela sua segurança','medo'),
('eu te entrego o dinheiro, por favor não me mate!','medo'),
('ele vai levar todo o meu dinheiro','medo'),
('não dirija tão rápido assim','medo'),
('me descobriram, irão me prender!','medo'),
('só espero que não me façam nenhum mal','medo'),
('vou me afogar, me ajudem a sair da água','medo'),
('não estaremos a salvo aqui','medo'),
('não quero nem pensar no que pode acontecer','medo'),
('nessa cidade e uma desgraça atrás da outra','medo'),
('alguem esta me ligando, estou assustado','medo'),
('isso não e remedio, não me matem','medo'),
('eu não confio nele, tenho que ter cautela','medo'),
('muita cautela','medo'),
('vou ser descoberto, meu deus','medo'),
('receio que terei de ir','medo'),
('a noite e muito perigosa','medo'),
('estou estremecendo com essa casa','medo'),
('olha aquela criatura se movendo monstruosamente','medo'),
('não agüento este suspense','medo'),
('afugente os cães','medo'),
('estou chocado e amedrontado com este assassinato brutal','medo'),
('e preciso afugenta com ímpeto este medo do inferno','medo'),
('seu políticos usam suas forças para afugentar e amedrontar o povo','medo'),
('o objetivo disso e apenas me amedrontar mais','medo'),
('isso me apavora','medo'),


    # RAIVA
('eu to com ódio dessa praga', 'raiva'),
('você tá me tirando do sério logo cedo', 'raiva'),
('pqp que encheção de saco','raiva'),
('quero meu dinheiro de volta','raiva'),
('ta pra nascer algo q me de mais dor de cabeça', 'raiva'),
('ele a feriu profundamente','raiva'),
('eu vou matar ele', 'raiva'),
('que droga, eu nao passei de ano na escola, pqp', 'raiva'),
('pqp, tomei dez multas de transito', 'raiva'),
('que droga, perdi tudo no cassino', 'raiva'),
('me roubaram na rua', 'raiva'),
('esse trouxa me deixou esperando', 'raiva'),
('vou despejar minha cólera em você','raiva'),
('me sinto atormentado','raiva'),
('não me contrarie','raiva'),
('meu time perdeu ontem', 'raiva'),
('so chove nesse lugar, que merda', 'raiva'),
('tirei ferias e fui despedido', 'raiva'),
('fui despedido por justa causa', 'raiva'),
('vou despedir aquele imcompetente', 'raiva'),
('bando de filho da puta, que raiva disso tudo', 'raiva'),
('nada mais faz sentido, que droga', 'raiva'),
('que lerdeza isso', 'raiva'),
('demora demais a fila', 'raiva'),
('nunca vai rapido a fila, sempre demora', 'raiva'),
('perdi todo meu dinheiro', 'raiva'),
('so tem gente feia nessa festa, vamos embora', 'raiva'),
('vou destruir tudo  que foi construído','raiva'),
('não consigo terminar este trabalho, e muito frustrante','raiva'),
('me frustra a sua presença aqui','raiva'),
('esta comida me parece muito ruim','raiva'),
('você me destrói','raiva'),
('estamos separados','raiva'),
('estou odiando este vestido','raiva'),
('não pude comprar meu celular hoje','raiva'),
('ela e uma garota ruim','raiva'),
('estivemos em um show horroroso','raiva'),
('o ingresso estava muito caro','raiva'),
('se eu estragar tudo vai por água a baixo','raiva'),
('não possuo dinheiro algum','raiva'),
('sou muito pobre','raiva'),
('vai prejudicar a todos esta nova medida','raiva'),
('ficou ridículo','raiva'),
('este sapato esta muito apertado','raiva'),
('a musica e uma ofensa aos meus ouvidos','raiva'),
('não consigo terminar uma tarefa muito difícil','raiva'),
('reprovei em minha graduação','raiva'),
('estou muito chateado com tudo','raiva'),
('eu odeio em você','raiva'),
('e um desprazer conhecê-lo','raiva'),
('estou desperdiçando minhas ferias','raiva'),
('e muito ruim este jogo','raiva'),
('vamos ter muito rancor pela frente','raiva'),
('não achei que seria tão terrível','raiva'),
('vou vetar o orçamento ao cliente','raiva'),
('meus pais não consentiram nosso casamento','raiva'),
('eu odiei este perfume','raiva'),
('seu descaso e frustrante','raiva'),
('me sinto completamente amarga','raiva'),
('desprezo muito o seu trabalho','raiva'),
('estamos descontentes por nossa família','raiva'),
('vou infernizar a sua empresa','raiva'),
('estou furioso com estes valores','raiva'),
('obrigaram o rapaz a sair','raiva'),
('como ele pode deixar de lado?','raiva'),
('são apenas injurias sobre mim','raiva'),
('estou enfurecido com a situação dessa empresa','raiva'),
('estou com o diabo no corpo','raiva'),
('isso foi diabólico','raiva'),
('tenho aversão à gente chata','raiva'),
('não vou perdoar sua traição','raiva'),
('esse dinheiro sujo e corrupto','raiva'),
('eles me crucificam o tempo todo','raiva'),
('eu vou enlouquecer com todo este barulho','raiva'),
('não agüento todo esse assedio','raiva'),
('cólera do dragão','raiva'),
('isso e ridículo!','raiva'),
('da próxima vez, vou inventar tudo sozinho','raiva'),
('seus tolos! deixaram ele escapar!','raiva'),
('jamais te perdoarei','raiva'),
('o que e isso? outra multa','raiva'),
('você passou dos limites!','raiva'),
('sente-se e cale a boca','raiva'),
('ingratosvermesvocês me pagam!','raiva'),
('saiam da dai, se não arranco vocês dai!','raiva'),
('você já me causou problemas suficientes','raiva'),
('que transito maldito, perdi muito tempo parado aqui nessa porra', 'raiva'),
('porra, eu nao quero esperar nada, sai da minha frente', 'raiva'),
('a bebida esquentou demais, estou muito puto com essa porra', 'raiva'),
('ele me traiu com aquela vadia, filho da puta', 'raiva'),
('uma palavra a mais e eu ja mandaria calar a boca', 'raiva'),
('eu nao tenho paciencia com gente lerda e burra', 'raiva'),
('preconceito me da muita raiva, que povo mais escroto', 'raiva'),
('estou nervoso com esta situacao, eu nao mereco passar esta barra sozinho, estou para matar alguem', 'raiva'),
('eu estou bastante  e mesma assim nao passei no tweet, que merda', 'raiva'),
('eu faco dieta e constinuo engordando', 'raiva'),
('isso foi a gota d’agua','raiva'),
('o que você tem com isso?','raiva'),
('não vejo a hora de me livrar de você','raiva'),
('já entendi a jogada seus safados!','raiva'),
('você não merece piedade','raiva'),
('saia de perto de mim','raiva'),
('suma daqui, ou arranco seu couro!','raiva'),
('estou revoltado com essa situação','raiva'),
('seu idiota!','raiva'),
('não, eu não vou te emprestar dinheiro!','raiva'),
('você não passa de um cafajeste! vai embora','raiva'),
('pare de frescura e vá trabalhar','raiva'),
('eles merecem uma lição','raiva'),
('ainda estou muito bravo com você','raiva'),
('eu preciso surrar aquela chantagista','raiva'),
('olha o que você fez! derramou!','raiva'),
('você está pedindo pra apanhar!','raiva'),
('me deixa em paz!','raiva'),
('morra maldito, morra!','raiva'),
('você e mais irritante de perto','raiva'),
('e bom fechar o bico','raiva'),
('Meu deus essa faculdade é uma merda','raiva'),
('VSF cara você não faz nada direito', 'raiva'),
('VSF seu imprestável', 'raiva'),
('VSF mano! sai daqui', 'raiva'),


    # SURPRESA
('magicamente você me surpreendeu','surpresa'),
('e imenso esse globo','surpresa'),
('uau que noticia bacana', 'surpresa'),
('uau, eu tambem quero um carro desse para mim', 'surpresa'),
('eu nao esperava ele me pedir em casamento, que noticia surpreendente', 'surpresa'),
('sera que iremos conseguir fugir?', 'surpresa'),
('descobri que estou gravida', 'surpresa'),
('qual o resultado do teste?', 'surpresa'),
('fascinante esse filme, eu adorei', 'surpresa'),
('que susto, eu nao esperava', 'surpresa'),
('ue, eu achei que iria chover hoje', 'surpresa'),
('nunca se sabe', 'surpresa'),
('quem sera o assassino', 'surpresa'),
('voce nunca sabera se e homem ou mulher', 'surpresa'),
('isso e tremendamente interessante','surpresa'),
('meu bilhete for sorteado, inacreditável!','surpresa'),
('um assalto a mão armada!','surpresa'),
('incrível, cabe em qualquer lugar!','surpresa'),
('você por aqui?','surpresa'),
('não dá pra acreditar no que ela me contou','surpresa'),
('os convidados já estão chegando!','surpresa'),
('puxa vida! nunca nos livramos de alguem tão depressa','surpresa'),
('micha carteira sumiu, eu estava com ela na mão','surpresa'),
('oh! um disco voador','surpresa'),
('amigos, que bela surpresa!','surpresa'),
('nunca pensei que veria isso e perto','surpresa'),
('nem acredito que comi tanto','surpresa'),
('não acredito que veio me ver','surpresa'),
('não acredito que e  tão descarado','surpresa'),
('me surpreende sua falta de tato','surpresa'),
('o predio onde eles moravam desabou!','surpresa'),
('inacreditável um bolo tão grande','surpresa'),
('e serio mesmo? não dá pra acreditar','surpresa'),
('como assim não vai ao nosso encontro?','surpresa'),
('como assim não tem ninguem em casa?','surpresa'),
('ue, mas para onde ele foi?!','surpresa'),
('por essa eu não esperava','surpresa'),
('nossa, olha só que mergulho','surpresa'),
('minha esposa está grávida!','surpresa'),
('meu dinheiro sumiu!','surpresa'),
('e verdade que os dois terminaram?!?','surpresa'),
('caramba, nem vi você chegar','surpresa'),
('nossa, como pode alguem cozinhar tão mal?','surpresa'),
('nossa que incrível','surpresa'),
('a fórmula sumiu!','surpresa'),
('eu nem acredito que já estou terminando o curso','surpresa'),
('não acredito que esta aqui comigo novamente','surpresa'),
('está escondendo algo de nós!','surpresa'),
('como assim, ainda não terminou a tarefa','surpresa'),
('pensei que já estivesse pronta!','surpresa'),
('opa! quem apagou a luz?','surpresa'),
('caramba! aonde vai tão rápido?','surpresa'),
('estamos seguindo o caminho errado!','surpresa'),
('quatro reais o litro da gasolina!','surpresa'),
('me assustei ao vê-lo desse jeito!','surpresa'),
('minha mãe está grávida, acredita nisso?','surpresa'),
('parece mentira você ter crescido tanto','surpresa'),
('me surpreende sua imaginação','surpresa'),
('suas roupas são realmente lindas','surpresa'),
('com consegue ser tão bela?','surpresa'),
('essa e realmente uma casa deslumbrante','surpresa'),
('superou minhas expectativas','surpresa'),
('e admirável a maneira como se comporta','surpresa'),
('isso e realmente chocante','surpresa'),
('algumas noticias me surpreenderam no noticiário','surpresa'),
('surpreendente sua festa','surpresa'),
('nossa, que top esse filme!, eu nao esperava', 'surpresa'),
('cheguei atrasado e me assim consegui entregar o resultado, ufa!', 'surpresa'),
('ufa, essa foi por pouco, quase caimos fora', 'surpresa'),
('quem sabe na proxima vida', 'surpresa'),
('estou tremendo de alegria','surpresa'),
('chocou grande parte do mundo','surpresa'),
('eu ficaria muito espantado com a sua vinda','surpresa'),
('ele e admirável','surpresa'),
('sua beleza me surpreendeu','surpresa'),
('seus olhos são surpreendentemente verdes','surpresa'),
('os políticos se surpreendem quando alguem acredita neles','surpresa'),
('estou perplexa com essas denuncias','surpresa'),
('fiquei perplexo com suas palavras','surpresa'),
('estou abismado com sua prosa','surpresa'),
('eu ficaria realmente abismado se me dissessem isso','surpresa'),
('o grupo foi surpreendido enquanto lavava o carro','surpresa'),
('estou boquiaberto com as imagens','surpresa'),
('estou boquiaberto com essas suas palavras','surpresa'),
('esse quadro e maravilhoso','surpresa'),
('este carro me deixou maravilhado','surpresa'),
('estou maravilhada','surpresa'),
('pqp, voce e gay?', 'surpresa'),
('qual sera o meu salario ano que vem?', 'surpresa'),
('essa expectativa esta me matando','surpresa'),
('vou caminhar sempre na expectativa de encontrá-lo','surpresa'),
('você emudece minhas palavras','surpresa'),
('minhas palavras vão emudecer se não parar de me surpreender','surpresa'),
('a mulher e um efeito deslumbrante da natureza','surpresa'),
('estou deslumbrada com essas jóias','surpresa'),
('isso e romântico e deslumbrante','surpresa'),
('isso pode ser surpreendentemente deslumbrante','surpresa'),
('trabalho deslumbrante','surpresa'),
('essas pessoas são esplêndida','surpresa'),
('e esplendido como o ceu se encontra no momento','surpresa'),
('e um carro fantástico','surpresa'),
('um edifício realmente fantástico','surpresa'),


    # TRISTEZA
('por favor não me abandone','tristeza'),
('não quero ficar sozinha','tristeza'),
('não me deixe sozinha','tristeza'),
('estou abatida','tristeza'),
('ele entrou em coma para sempre, que dó', 'tristeza'),
('uma bacteria matou a populacao inteira', 'tristeza'),
('a miseria tomou conta do pais todo', 'tristeza'),
('pobreza e miseria matam todos de fome no mundo', 'tristeza'),
('eu nao aguento mais viver sem ele', 'tristeza'),
('eu trabalho muito e nao ganho nada, e triste', 'tristeza'),
('cancer e triste demais', 'tristeza'),
('qualquer doenca e terrivel', 'tristeza'),
('sofrer acidente com trauma e muito dramatico', 'tristeza'),
('saber que funkeiro ganha mais que professor e de doer o coracao', 'tristeza'),
('bati o carro no poste, me ferrei', 'tristeza'),
('acabaram minhas ferias', 'tristeza'),
('ficar doente e muito ruim', 'tristeza'),
('ele me traiu com um vadia', 'tristeza'),
('meus pais estao doentes', 'tristeza'),
('depressao e uma doenca silenciosa e mortal', 'tristeza'),
('ela perdeu o emprego e entrou em depressao profunda', 'tristeza'),
('amputar um membro devido a doenca e triste demais', 'tristeza'),
('filhos pequenos foram separados dos pais na fronteira, que tristeza', 'tristeza'),
('os animais sao cacados e mortos a toa, sem razao nenhuma, eu morro de dó', 'tristeza'),
('sacrificar os animais devido a ganancia e muito triste', 'tristeza'),
('e bizarro o quanto morre de fome na africa', 'tristeza'),
('qualquer doenca que cause sequelas e terrivel', 'tristeza'),
('a guerra so traz destruicao e pobreza', 'tristeza'),
('saudade faz muito mal para o coracao', 'tristeza'),
('ele esta todo abatido','tristeza'),
('tão triste suas palavras','tristeza'),
('seu amor não e mais meu','tristeza'),
('estou aborrecida','tristeza'),
('isso vai me aborrecer','tristeza'),
('estou com muita aflição','tristeza'),
('me aflige o modo como fala','tristeza'),
('estou em agonia com meu intimo','tristeza'),
('não quero fazer nada','tristeza'),
('me sinto ansiosa e tensa','tristeza'),
('não consigo parar de chorar','tristeza'),
('não consigo segurar as lagrimas','tristeza'),
('e muita dor perder um ente querido','tristeza'),
('estou realmente arrependida','tristeza'),
('acho que o carma volta, pois agora sou eu quem sofro','tristeza'),
('você não cumpriu suas promessas','tristeza'),
('me sinto amargurada','tristeza'),
('coitado esta tão triste','tristeza'),
('já e tarde de mais','tristeza'),
('nosso amor acabou','tristeza'),
('essa noite machuca só para mim','tristeza'),
('eu não estou mais no seu coração','tristeza'),
('você mudou comigo','tristeza'),
('quando eu penso em você realmente dói','tristeza'),
('como se fosse nada você vê minhas lagrimas','tristeza'),
('você disse cruelmente que não se arrependeu','tristeza'),
('eu nunca mais vou te ver','tristeza'),
('ela esta com depressão','tristeza'),
('a depressão aflige as pessoas','tristeza'),
('estar depressivo e muito ruim','tristeza'),
('estou derrotada e deprimida depois deste dia','tristeza'),
('e comovente te ver dessa maneira','tristeza'),
('e comovente ver o que os filhos do brasil passam','tristeza'),
('como me sinto culpada','tristeza'),
('estou abatida','tristeza'),
('a ansiedade tomou conta de mim','tristeza'),
('as pessoas não gostam do meu jeito','tristeza'),
('adeus passamos bons momentos juntos','tristeza'),
('sinto sua falta','tristeza'),
('ele não gostou da minha comida','tristeza'),
('estou sem dinheiro para a comida','tristeza'),
('queria que fosse o ultimo dia da minha vida','tristeza'),
('você está com vergonha de mim','tristeza'),
('ela não aceitou a minha proposta','tristeza'),
('era o meu ultimo centavo','tristeza'),
('reprovei de ano na faculdade','tristeza'),
('afinal você só sabe me desfazer','tristeza'),
('eu falhei em tudo nessa vida','tristeza'),
('eu fui muito humilhado','tristeza'),
('e uma história muito triste','tristeza'),
('ninguem acredita em mim','tristeza'),
('eu não sirvo para nada mesmo','tristeza'),
('droga, não faço nada direito','tristeza'),
('sofrimento em dobro na minha vida','tristeza'),
('fui demitida essa semana','tristeza'),
('as crianças sofrem ainda mais que os adultos','tristeza'),
('pra mim um dia e ruim, o outro e pior','tristeza'),
('de repente perdi o apetite','tristeza'),
('oh que dia infeliz','tristeza'),
('estamos afundados em contas','tristeza'),
('nem um milagre pode nos salvar','tristeza'),
('só me resta a esperança','tristeza'),
('pior que isso não pode ficar','tristeza'),
('meu salário e baixo','tristeza'),
('não passei no vestibular','tristeza'),
('ninguem se importa comigo','tristeza'),
('ninguem lembrou do meu aniversário','tristeza'),
('tenho tanto azar','tristeza'),
('o gosto da vingança e amargo','tristeza'),
('sou uma mulher amargurada depois de que você me deixou','tristeza'),
('estou desanimada com a vida','tristeza'),
('e um desanimo só coitadinha','tristeza'),
('a derrota e depressiva','tristeza'),
('discriminar e desumano','tristeza'),
('que desanimo','tristeza'),
('e uma desonra para o pais','tristeza'),
('a preocupação deveria nos levar a ação não a depressão','tristeza'),
('passamos ao desalento e a loucura','tristeza'),
('aquele que nunca viu a tristeza nunca reconhecerá a alegria','tristeza'),
('cuidado com a tristeza ela e um vicio','tristeza')]
