# Generated by Django 4.0.3 on 2022-03-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbase',
            name='sentimento',
            field=models.CharField(choices=[('positivo', 'positivo'), ('neutro', 'neutro'), ('negativo', 'negativo')], max_length=20, verbose_name='Sentimento'),
        ),
        migrations.AlterField(
            model_name='trainingbaseadvanced',
            name='sentimento',
            field=models.CharField(choices=[('alegria', 'alegria'), ('nojo', 'nojo'), ('medo', 'medo'), ('raiva', 'raiva'), ('surpresa', 'surpresa'), ('tristeza', 'tristeza')], max_length=20, verbose_name='Sentimento'),
        ),
    ]
