# Generated by Django 4.0.3 on 2022-03-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='bearerToken',
            field=models.CharField(default='DEFAULT', max_length=150, verbose_name='Bearer Token'),
        ),
    ]
