# Generated by Django 4.0.3 on 2022-05-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='fone',
        ),
    ]
