# Generated by Django 4.0.3 on 2022-05-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customusuario_fone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='accessToken',
        ),
        migrations.RemoveField(
            model_name='customusuario',
            name='accessTokenSecret',
        ),
        migrations.RemoveField(
            model_name='customusuario',
            name='consumerKey',
        ),
        migrations.RemoveField(
            model_name='customusuario',
            name='consumerSecret',
        ),
    ]
