# Generated by Django 4.0.3 on 2022-05-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_customusuario_accesstoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
