# Generated by Django 4.0.3 on 2022-05-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_customusuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='bearerToken',
            field=models.CharField(max_length=150, verbose_name='Bearer Token'),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Membro da equipe'),
        ),
    ]
