# Generated by Django 4.0.3 on 2022-03-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBaseAdvanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('texto', models.TextField(max_length=300, verbose_name='Texto')),
                ('sentimento', models.CharField(max_length=100, verbose_name='Sentimento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
